-- Enable UUID extension if not already enabled
create extension if not exists "uuid-ossp";

-- GROUPS TABLE
create table if not exists groups (
  id bigint generated by default as identity primary key,
  name text not null,
  level text, -- e.g., 'Débutant', 'Intermédiaire'
  age_range text, -- e.g., '8-10 ans'
  establishment text, -- e.g., 'École Primaire Pasteur'
  main_theme text, -- e.g., 'Robotique'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- GROUP MEMBERS TABLE
create table if not exists group_members (
  id bigint generated by default as identity primary key,
  group_id bigint references groups(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade, -- Link to Supabase Auth Users
  role text not null check (role in ('apprenant', 'animateur', 'admin')) default 'apprenant',
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(group_id, user_id)
);

-- GROUP SESSIONS TABLE (Planning)
create table if not exists group_sessions (
  id bigint generated by default as identity primary key,
  group_id bigint references groups(id) on delete cascade not null,
  title text,
  description text,
  date_session date not null,
  start_time time not null,
  end_time time not null,
  location text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ATTENDANCE TABLE
create table if not exists attendance (
  id bigint generated by default as identity primary key,
  session_id bigint references group_sessions(id) on delete cascade not null,
  member_id bigint references group_members(id) on delete cascade not null,
  status text not null check (status in ('present', 'absent', 'late', 'excused')) default 'present',
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(session_id, member_id)
);

-- RLS POLICIES (Basic Draft - customize as needed)
alter table groups enable row level security;
alter table group_members enable row level security;
alter table group_sessions enable row level security;
alter table attendance enable row level security;

-- For now, allow public read access for dev/mvp simplicity, or restricted to authenticated
create policy "Public read access" on groups for select using (true);
create policy "Authenticated insert" on groups for insert to authenticated with check (true);
create policy "Authenticated update" on groups for update to authenticated using (true);
create policy "Authenticated delete" on groups for delete to authenticated using (true);

-- Same for others (simplify for MVP)
create policy "Public read access" on group_members for select using (true);
create policy "Authenticated all" on group_members for all to authenticated using (true);

create policy "Public read access" on group_sessions for select using (true);
create policy "Authenticated all" on group_sessions for all to authenticated using (true);

create policy "Public read access" on attendance for select using (true);
create policy "Authenticated all" on attendance for all to authenticated using (true);
