-- Create table for group resources
create table if not exists group_resources (
  id bigint generated by default as identity primary key,
  group_id bigint references groups(id) on delete cascade not null,
  title text not null,
  file_url text not null,
  file_type text not null check (file_type in ('file', 'link')),
  uploaded_by uuid references auth.users(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for group_resources
alter table group_resources enable row level security;

create policy "Group resources are viewable by everyone (for now, or restrict to group members)"
  on group_resources for select
  using ( true );

create policy "Authenticated users can upload resources"
  on group_resources for insert
  with check ( auth.role() = 'authenticated' );

create policy "Users can delete their own resources or admins"
  on group_resources for delete
  using ( auth.uid() = uploaded_by ); -- Simplified for MVP

-- STORAGE POLICIES (Assuming bucket 'group-resources' exists)
-- You must create the bucket 'group-resources' in the Supabase Dashboard > Storage

-- Allow public access to read files in the bucket
create policy "Give public access to group-resources"
  on storage.objects for select
  using ( bucket_id = 'group-resources' );

-- Allow authenticated uploads
create policy "Allow authenticated uploads to group-resources"
  on storage.objects for insert
  with check ( bucket_id = 'group-resources' and auth.role() = 'authenticated' );

-- Allow deletions
create policy "Allow internal deletions"
  on storage.objects for delete
  using ( bucket_id = 'group-resources' and auth.role() = 'authenticated' );
