-- EVALUATIONS TABLE (Suivi Pédagogique)
create table if not exists evaluations (
  id bigint generated by default as identity primary key,
  member_id bigint references group_members(id) on delete cascade not null,
  author_id uuid references auth.users(id), -- The trainer who wrote the note
  content text not null,
  type text not null check (type in ('observation', 'feedback', 'grade')) default 'observation',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS
alter table evaluations enable row level security;

-- Allow public access for Admin (NextAuth/Anon client) as per current dev setup
create policy "Public all" on evaluations for all using (true);
