INSERT INTO "public"."ateliers" (
    "id",
    "slug",
    "titre",
    "description",
    "objectifs",
    "public_cible",
    "duree_heures",
    "tarif_eur",
    "materiel",
    "image_url",
    "created_at",
    "categorie",
    "type",
    "sequence_order",
    "updated_at",
    "title",
    "shortdescription",
    "longdescription",
    "learningobjectives",
    "targetaudience",
    "agegroup",
    "duration",
    "price",
    "materials",
    "category",
    "categorycolor",
    "discipline",
    "format",
    "tags"
  )
VALUES (
    1,
    'chimie-ludique',
    'Chimie Ludique',
    'Atelier pratique pour découvrir réactions et états de la matière via expériences sécurisées.',
    ARRAY ['Observer réactions chimiques','Utiliser matériel de laboratoire en sécurité'],
    'Primaire',
    '2',
    '180',
    'Kits chimie non toxiques; lunettes; gants',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/CHIMIE%20AMUSANTE.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvQ0hJTUlFIEFNVVNBTlRFLnBuZyIsImlhdCI6MTc3ODI4Njc2MCwiZXhwIjoxODcyODk0NzYwfQ.KoIEUsgIyRxKvIFnOK9O2j3a3FqM3jvRg4JWCkH5Qj8',
    '2026-05-08 00:00:00',
    'sciences',
    'workshop',
    1,
    '2026-05-10 07:25:51.912942+00',
    'Chimie Ludique',
    'Expériences sûres et visuelles pour comprendre réactions et états de la matière.',
    'Atelier pratique avec expériences guidées (réactions colorées, mousse, indicateurs pH). Sécurité et manipulation encadrées. Déroulé : introduction 15 min; 4 expériences 90 min; restitution 15 min.',
    ARRAY ['Observer réactions chimiques','Utiliser matériel de laboratoire en sécurité'],
    'Écoles primaires, centres de loisirs',
    '7-11 ans',
    '2 heures',
    '180',
    'Kits chimie non toxiques; lunettes; gants',
    'Sciences & Expériences',
    '#0097b2',
    'sciences_experiences',
    'Séance unique;Cycle trimestriel',
    ARRAY ['chimie','expériences','primaire']
  ),
  (
    2,
    'electricite-circuits',
    'Électricité et Circuits',
    'Atelier pratique sur montage de circuits, capteurs et moteurs.',
    ARRAY ['Comprendre circuit série/parallèle','Utiliser multimètre'],
    'Collège',
    '2',
    '200',
    'Breadboards; composants; multimètre',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/ELECTRICITE_CIRCUITS.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvRUxFQ1RSSUNJVEVfQ0lSQ1VJVFMucG5nIiwiaWF0IjoxNzc4Mjg2NzA2LCJleHAiOjE4NzI4OTQ3MDZ9.i7oLuTBKuJMUAeidHMzOUOgcxw0Mu_HPmNcSb-a_pi4',
    '2026-05-08 00:00:00',
    'sciences',
    'workshop',
    2,
    '2026-05-10 07:25:51.912942+00',
    'Électricité et Circuits',
    'Construire circuits simples, comprendre tension, courant et sécurité.',
    'Montage de circuits en série/parallèle, utilisation de capteurs et LED, introduction aux moteurs. Déroulé : théorie 20 min; ateliers pratiques 80 min; mini-projet 20 min.',
    ARRAY ['Comprendre circuit série/parallèle','Souder ou connecter composants de base'],
    'Collèges, lycées',
    '11-15 ans',
    '2 heures',
    '200',
    'Breadboards; composants; multimètre',
    'Sciences & Expériences',
    '#0097b2',
    'sciences_experiences',
    'Séance unique;Cycle trimestriel;Cycle annuel',
    ARRAY ['électricité','électronique']
  ),
  (
    3,
    'robotique-ludique',
    'Robotique Ludique',
    'Atelier montage et programmation de robots pour missions ludiques.',
    ARRAY ['Assembler robot simple','Programmer capteurs'],
    'Collège',
    '2',
    '220',
    'Kits robotique; tablettes',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/robotique-creative.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvcm9ib3RpcXVlLWNyZWF0aXZlLmpwZyIsImlhdCI6MTc3ODI4ODAxOCwiZXhwIjoxODcyODk2MDE4fQ.292bFAAevq7wCnKUt37mGCV-XLmuN_sjGhmzc1mzYeQ',
    '2026-05-08 00:00:00',
    'robotique-ia',
    'workshop',
    3,
    '2026-05-10 07:25:51.912942+00',
    'Robotique Ludique',
    'Construire un robot simple et le programmer pour réaliser des missions.',
    'Assemblage d''un châssis, moteurs, capteurs de distance, programmation bloc (Scratch/Blockly). Déroulé : montage 45 min; programmation 60 min; défis 15 min.',
    ARRAY ['Assembler robot simple','Programmer déplacements et capteurs'],
    'Collèges, centres de loisirs',
    '10-14 ans',
    '2 heures',
    '220',
    'Kits robotique; tablettes',
    'Robotique & IA',
    '#0a714e',
    'robotique_ia',
    'Séance unique;Cycle trimestriel;Hackathon',
    ARRAY ['robotique','programmation']
  ),
  (
    4,
    'initiation-ia',
    'Initiation à l''IA',
    'Atelier d''initiation aux concepts et applications de l''intelligence artificielle.',
    ARRAY ['Comprendre pipeline IA','Expérimenter classification simple'],
    'Collège/Lycée',
    '4',
    '320',
    'Ordinateurs; datasets pédagogiques; outils no-code',
    'https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=2070',
    '2026-05-08 00:00:00',
    'robotique-ia',
    'workshop',
    4,
    '2026-05-10 07:25:51.912942+00',
    'Initiation à l''IA',
    'Comprendre les bases de l''intelligence artificielle via projets simples.',
    'Notions de données, modèles, entraînement et biais. Atelier pratique : classification d''images simple, démonstration d''outils no-code. Déroulé : théorie 60 min; atelier 150 min; restitution 30 min.',
    ARRAY ['Comprendre pipeline IA','Expérimenter classification simple'],
    'Collège, Lycée',
    '13-17 ans',
    '4 heures',
    '320',
    'Ordinateurs; datasets pédagogiques; outils no-code',
    'Robotique & IA',
    '#0a714e',
    'robotique_ia',
    'Demi-journée;Cycle semestriel',
    ARRAY ['IA','données','éthique']
  ),
  (
    5,
    'scratch-creation-jeux',
    'Scratch et Création de Jeux',
    'Atelier de programmation par blocs pour créer un jeu interactif.',
    ARRAY ['Structurer algorithmes simples','Utiliser variables et événements'],
    'Primaire',
    '2',
    '160',
    'Ordinateurs; comptes Scratch',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/Scratch%20et%20Creation%20de%20Jeux.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvU2NyYXRjaCBldCBDcmVhdGlvbiBkZSBKZXV4LnBuZyIsImlhdCI6MTc3ODI4NzMzNSwiZXhwIjoxODcyODk1MzM1fQ.WjPQuF9s_mc5ptCrc7poCGgQzlIMgIbj9PLZ8LEb9Tk',
    '2026-05-08 00:00:00',
    'numerique-code',
    'workshop',
    5,
    '2026-05-10 07:25:51.912942+00',
    'Scratch et Création de Jeux',
    'Créer un jeu interactif avec Scratch pour apprendre la logique de programmation.',
    'Conception d''un jeu (personnage, collisions, score), introduction aux variables et boucles. Déroulé : brief 15 min; atelier 90 min; partage 15 min.',
    ARRAY ['Structurer algorithmes simples','Utiliser variables et événements'],
    'Primaire, Collège',
    '8-12 ans',
    '2 heures',
    '160',
    'Ordinateurs; comptes Scratch',
    'Numérique & Code',
    '#4910bc',
    'numerique_code',
    'Séance unique;Cycle trimestriel;Stage vacances',
    ARRAY ['scratch','programmation','primaire']
  ),
  (
    6,
    'python-debutant',
    'Python Débutant',
    'Atelier pratique pour apprendre les bases de Python et réaliser un mini-projet.',
    ARRAY ['Écrire scripts simples','Décomposer problèmes en fonctions'],
    'Collège/Lycée',
    '4',
    '280',
    'Ordinateurs; IDE léger',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/Python-Debutant.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvUHl0aG9uLURlYnV0YW50LmpwZyIsImlhdCI6MTc3ODI4Njk0NSwiZXhwIjoxODcyODk0OTQ1fQ.09LXEYmsnre4wQTicZPaX9i-YiCf5nq11aj46ObHDSk',
    '2026-05-08 00:00:00',
    'numerique-code',
    'workshop',
    6,
    '2026-05-10 07:25:51.912942+00',
    'Python Débutant',
    'Bases de Python : variables, boucles, fonctions et mini-projet.',
    'Atelier pratique sur environnement Python, exercices guidés et mini-projet (jeu texte ou mini-calculateur). Déroulé : 45 min théorie; 150 min pratique; 15 min restitution.',
    ARRAY ['Écrire scripts simples','Décomposer problèmes en fonctions'],
    'Collège, Lycée',
    '12-17 ans',
    '4 heures',
    '280',
    'Ordinateurs; IDE léger',
    'Numérique & Code',
    '#4910bc',
    'numerique_code',
    'Demi-journée;Cycle semestriel',
    ARRAY ['python','programmation']
  ),
  (
    7,
    'numerique-responsable',
    'Numérique Responsable',
    'Atelier de sensibilisation à la sobriété numérique, sécurité et éthique.',
    ARRAY ['Réduire empreinte numérique','Identifier sources fiables'],
    'Collège/Lycée',
    '2',
    '150',
    'Supports pédagogiques; quiz interactif',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/numerique_responsable.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvbnVtZXJpcXVlX3Jlc3BvbnNhYmxlLnBuZyIsImlhdCI6MTc3ODY2MjAwNCwiZXhwIjoxODczMjcwMDA0fQ.zJwQSW5w03z_FPfeUwXL8GdNgWVXG9lHmE4TI_QuWJk',
    '2026-05-08 00:00:00',
    'numerique-responsable',
    'workshop',
    7,
    '2026-05-10 07:25:51.912942+00',
    'Numérique Responsable',
    'Bonnes pratiques, empreinte numérique et sécurité en ligne.',
    'Atelier interactif sur sobriété numérique, gestion des données, mots de passe, fake news. Déroulé : cas pratiques, quiz et atelier de création d''une charte numérique.',
    ARRAY ['Réduire empreinte numérique','Identifier sources fiables'],
    'Collège, Lycée',
    '12-17 ans',
    '2 heures',
    '150',
    'Supports pédagogiques; quiz interactif',
    'Numérique responsable',
    '#e96b1f',
    'numerique_responsable',
    'Séance unique;Cycle trimestriel',
    ARRAY ['cybersécurité','sobriété']
  ),
  (
    8,
    'fake-news-verification',
    'Fake News et Vérification',
    'Atelier pratique pour apprendre à vérifier l''information en ligne.',
    ARRAY ['Utiliser outils de vérification','Analyser sources'],
    'Collège/Lycée',
    '2',
    '150',
    'Ordinateurs; fiches méthodologiques',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/fakenews.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvZmFrZW5ld3MuanBnIiwiaWF0IjoxNzc4Mjg4MTc2LCJleHAiOjE4NzI4OTYxNzZ9.8a_o-15G7piwATYaJbIGTl1TlP6w5hG5zXEjiwexCU0',
    '2026-05-08 00:00:00',
    'numerique-responsable',
    'workshop',
    8,
    '2026-05-10 07:25:51.912942+00',
    'Fake News et Vérification',
    'Méthodes pour vérifier sources, images et vidéos en ligne.',
    'Atelier pratique avec études de cas, outils de vérification et création d''un guide de vérification pour la classe.',
    ARRAY ['Utiliser outils de vérification','Analyser sources'],
    'Collège, Lycée',
    '13-17 ans',
    '2 heures',
    '150',
    'Ordinateurs; fiches méthodologiques',
    'Numérique responsable',
    '#e96b1f',
    'numerique_responsable',
    'Séance unique;Cycle trimestriel',
    ARRAY ['esprit critique','médias']
  ),
  (
    9,
    'jardin-scientifique',
    'Jardin Scientifique',
    'Atelier terrain sur biodiversité, sol et suivi de plantations.',
    ARRAY ['Observer biodiversité','Mesurer paramètres du sol'],
    'Primaire/Collège',
    '2',
    '170',
    'Kits jardinage; loupes; fiches terrain',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/JARDINAGE_SCIENTIFIQUE.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvSkFSRElOQUdFX1NDSUVOVElGSVFVRS5wbmciLCJpYXQiOjE3NzgyODU1ODMsImV4cCI6MTg3Mjg5MzU4M30.CC8kJpqDr1ymjXSV4s3TehjGvJLj-mI6YyyH3XvCMlU',
    '2026-05-08 00:00:00',
    'ecologie-vie',
    'workshop',
    9,
    '2026-05-10 07:25:51.912942+00',
    'Jardin Scientifique',
    'Découvrir biodiversité, sol et cycles via un projet jardinage scientifique.',
    'Observation de la biodiversité, mesures du sol, semis et suivi. Déroulé : introduction 20 min; atelier terrain 80 min; carnet de bord 20 min.',
    ARRAY ['Observer biodiversité','Mesurer paramètres du sol'],
    'Primaire, Collège',
    '8-14 ans',
    '2 heures',
    '170',
    'Kits jardinage; loupes; fiches terrain',
    'Écologie & Sciences de la Vie',
    '#4ca626',
    'ecologie_sciences_vie',
    'Séance unique;Cycle trimestriel;Projet sur-mesure',
    ARRAY ['écologie','terrain']
  ),
  (
    10,
    'biodiversite-microhabitats',
    'Biodiversité et Microhabitats',
    'Atelier d''inventaire et d''analyse écologique locale.',
    ARRAY ['Identifier espèces locales','Utiliser protocoles d''inventaire'],
    'Collège',
    '2',
    '180',
    'Guides d''identification; fiches; loupes',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/BIODIVERSITE_LOCALE.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvQklPRElWRVJTSVRFX0xPQ0FMRS5wbmciLCJpYXQiOjE3NzgyODU0NzYsImV4cCI6MTg3Mjg5MzQ3Nn0.obHyh8vI1KE18RGMqM6zo2n2LIWrnmn2g9YT_uUt7pY',
    '2026-05-08 00:00:00',
    'ecologie-vie',
    'workshop',
    10,
    '2026-05-10 07:25:51.912942+00',
    'Biodiversité et Microhabitats',
    'Étude des microhabitats locaux et inventaire d''espèces.',
    'Méthodes d''inventaire, identification d''espèces, création d''un atlas local. Déroulé : méthodologie 20 min; terrain 80 min; synthèse 20 min.',
    ARRAY ['Identifier espèces locales','Utiliser protocoles d''inventaire'],
    'Collège',
    '11-15 ans',
    '2 heures',
    '180',
    'Guides d''identification; fiches; loupes',
    'Écologie & Sciences de la Vie',
    '#4ca626',
    'ecologie_sciences_vie',
    'Séance unique;Cycle trimestriel;Projet sur-mesure',
    ARRAY ['biodiversité','inventaire']
  ),
  (
    11,
    'fusees-propulsion',
    'Fusées et Propulsion',
    'Atelier sur principes de propulsion et construction de maquettes de fusées.',
    ARRAY ['Comprendre poussée et traînée','Concevoir maquette stable'],
    'Collège/Lycée',
    '2',
    '200',
    'Kits fusée eau; pompe; cibles de sécurité',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/FUSEES_EAU.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvRlVTRUVTX0VBVS5wbmciLCJpYXQiOjE3NzgyODcyOTcsImV4cCI6MTg3Mjg5NTI5N30.UPMQrxpRTAFQcAI0qF00VckpiiI4vH1J_EywZbKZwwk',
    '2026-05-08 00:00:00',
    'espace-aeronautique',
    'workshop',
    11,
    '2026-05-10 07:25:51.912942+00',
    'Fusées et Propulsion',
    'Concevoir et lancer des maquettes de fusées, comprendre principes de propulsion.',
    'Étude forces, poussée, aérodynamique; construction et essais de petites fusées à eau ou à air comprimé. Déroulé : théorie 30 min; construction 70 min; lancements 20 min.',
    ARRAY ['Comprendre poussée et traînée','Concevoir maquette stable'],
    'Collège, Lycée',
    '12-17 ans',
    '2 heures',
    '200',
    'Kits fusée eau; pompe; cibles de sécurité',
    'Espace & Aéronautique',
    '#004aad',
    'espace_aeronotique',
    'Séance unique;Journée science;Stage vacances',
    ARRAY ['espace','fusées']
  ),
  (
    12,
    'satellites-missions',
    'Satellites et Missions',
    'Atelier projet sur conception de mission satellite et simulation d''orbites.',
    ARRAY ['Comprendre orbites','Concevoir mission simple'],
    'Collège/Lycée',
    '4',
    '340',
    'Ordinateurs; simulateur orbital; maquettes',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/MISSION_SPATIALE.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvTUlTU0lPTl9TUEFUSUFMRS5wbmciLCJpYXQiOjE3NzgyODgyNTMsImV4cCI6MTg3Mjg5NjI1M30.e3ydmgq5RfVyw_ndKZgIO7jaBIOCPm-1NYz_5h5QIjU',
    '2026-05-08 00:00:00',
    'espace-aeronautique',
    'workshop',
    12,
    '2026-05-10 07:25:51.912942+00',
    'Satellites et Missions',
    'Concevoir une mission satellite miniature et simuler orbites.',
    'Notions d''orbite, télédétection, capteurs. Atelier projet : concevoir mission, choisir capteurs, simuler orbite et restitution.',
    ARRAY ['Comprendre orbites','Concevoir mission simple'],
    'Collège, Lycée',
    '13-17 ans',
    '4 heures',
    '340',
    'Ordinateurs; simulateur orbital; maquettes',
    'Espace & Aéronautique',
    '#004aad',
    'espace_aeronotique',
    'Demi-journée;Cycle semestriel',
    ARRAY ['satellites','orbites']
  ),
  (
    13,
    'impression-3d-fabrication',
    'Impression 3D et Fabrication',
    'Atelier de modélisation et impression 3D pour créer des pièces fonctionnelles.',
    ARRAY ['Modéliser en 3D','Préparer impression'],
    'Collège/Lycée',
    '3',
    '260',
    'Imprimantes 3D; filament; postes CAO',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/Mini_Impression_3D.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvTWluaV9JbXByZXNzaW9uXzNELmpwZyIsImlhdCI6MTc3ODI4NzI0MiwiZXhwIjoxODcyODk1MjQyfQ.VTLwmzH4KErM8fiWhe9gfEVEiN-bCaEs60Xn9NAP_y8',
    '2026-05-08 00:00:00',
    'numerique-code',
    'workshop',
    13,
    '2026-05-10 07:25:51.912942+00',
    'Impression 3D et Fabrication',
    'Concevoir en 3D et fabriquer une pièce fonctionnelle.',
    'Initiation à la modélisation (Tinkercad/FreeCAD), préparation fichier, impression et post-traitement. Déroulé : modélisation 90 min; impression démonstration 60 min; finition 30 min.',
    ARRAY ['Modéliser en 3D','Préparer impression'],
    'Collège, Lycée',
    '12-17 ans',
    '3 heures',
    '260',
    'Imprimantes 3D; filament; postes CAO',
    'Numérique & Code',
    '#4910bc',
    'numerique_code',
    'Demi-journée;Cycle semestriel;Stage vacances',
    ARRAY ['3D','makers']
  ),
  (
    14,
    'electronique-creative',
    'Électronique Créative',
    'Atelier de prototypage électronique avec microcontrôleurs et capteurs.',
    ARRAY ['Programmer microcontrôleur','Intégrer capteurs'],
    'Collège/Lycée',
    '2',
    '200',
    'Microcontrôleurs; capteurs; câbles',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/Electronique_Creative.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvRWxlY3Ryb25pcXVlX0NyZWF0aXZlLmpwZyIsImlhdCI6MTc3ODI4Nzg0MCwiZXhwIjoxODcyODk1ODQwfQ.OC4RBe8F8Kzuq0wJzpx6yK5B8PsUNpAsT-WOuQmPz9I',
    '2026-05-08 00:00:00',
    'sciences',
    'workshop',
    14,
    '2026-05-10 07:25:51.912942+00',
    'Électronique Créative',
    'Projets électroniques ludiques : wearables, cartes microcontrôleurs.',
    'Utilisation d''Arduino ou micro:bit pour créer objets interactifs (capteurs, LEDs, son). Déroulé : présentation 20 min; prototypage 80 min; démonstration 20 min.',
    ARRAY ['Programmer microcontrôleur','Intégrer capteurs'],
    'Collège, Lycée',
    '12-17 ans',
    '2 heures',
    '200',
    'Microcontrôleurs; capteurs; câbles',
    'Sciences & Expériences',
    '#0097b2',
    'sciences_experiences',
    'Séance unique;Cycle trimestriel;Stage vacances',
    ARRAY ['électronique','microcontrôleur']
  ),
  (
    15,
    'makers-junior',
    'Makers Junior',
    'Atelier créatif et manuel pour initier les plus jeunes au making.',
    ARRAY ['Développer motricité fine','Comprendre mécanismes simples'],
    'Primaire',
    '2',
    '160',
    'Matériel de bricolage; consommables; kits simples',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/Makers_Junior.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvTWFrZXJzX0p1bmlvci5qcGciLCJpYXQiOjE3NzgyODY5OTQsImV4cCI6MTg3Mjg5NDk5NH0.TxQXSDhYVUzpiLxHVpHcf6kTV0HLrRIxFWLKh1JhgP8',
    '2026-05-08 00:00:00',
    'numerique-code',
    'workshop',
    15,
    '2026-05-10 07:25:51.912942+00',
    'Makers Junior',
    'Initiation à la fabrication et au bricolage scientifique pour les plus jeunes.',
    'Projets simples : circuits papier, maquettes, petits mécanismes. Déroulé : démonstration 15 min; atelier 90 min; exposition 15 min.',
    ARRAY ['Développer motricité fine','Comprendre mécanismes simples'],
    'Primaire',
    '6-9 ans',
    '2 heures',
    '160',
    'Matériel de bricolage; consommables; kits simples',
    'Numérique & Code',
    '#4910bc',
    'numerique_code',
    'Séance unique;Stages vacances',
    ARRAY ['makers','primaire']
  ),
  (
    16,
    'projets-stem-avances',
    'Projets STEM Avancés',
    'Cycle projet interdisciplinaire pour lycéens, prototypage et restitution.',
    ARRAY ['Gérer projet technique','Intégrer disciplines STEM'],
    'Lycée',
    '6',
    '520',
    'Atelier complet; imprimante 3D; kits robotique; PC',
    'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=2070',
    '2026-05-08 00:00:00',
    'sciences',
    'workshop',
    16,
    '2026-05-10 07:25:51.912942+00',
    'Projets STEM Avancés',
    'Cycle intensif pour concevoir un projet interdisciplinaire (robotique, IA, fabrication).',
    'Accompagnement projet de A à Z : cadrage, prototypage, tests et restitution devant jury. Idéal pour TPE/option scientifique. Déroulé sur une journée complète ou 2 demi-journées.',
    ARRAY ['Gérer projet technique','Intégrer disciplines STEM'],
    'Lycée',
    '15-18 ans',
    '6 heures',
    '520',
    'Atelier complet; imprimante 3D; kits robotique; PC',
    'Sciences & Expériences',
    '#0097b2',
    'sciences_experiences',
    'Journée complète;Cycle annuel',
    ARRAY ['projet','lycée']
  ),
  (
    17,
    'hackathon-scolaire',
    'Hackathon Scolaire',
    'Journée de compétition pour prototyper et pitcher des solutions innovantes.',
    ARRAY ['Travailler en équipe','Prototyper rapidement'],
    'Collège/Lycée',
    '8',
    '900',
    'Kits; mentors; matériel événementiel',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/Hackathon_Scolaire%20.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvSGFja2F0aG9uX1Njb2xhaXJlIC5qcGciLCJpYXQiOjE3NzgyODYxMDMsImV4cCI6MTg3Mjg5NDEwM30.iPxwAH709ttbUlimDP-9Wqusdpk8WZcxAScjOOMqTq8',
    '2026-05-08 00:00:00',
    'robotique-ia',
    'workshop',
    17,
    '2026-05-10 07:25:51.912942+00',
    'Hackathon Scolaire',
    'Compétition d''innovation 1 journée pour prototyper une solution en équipe.',
    'Organisation clé en main : brief, mentors, matériel, jury et remise de prix. Thématiques adaptables (écologie, mobilité, inclusion). Déroulé : matin cadrage; après-midi prototypage; fin de journée pitchs.',
    ARRAY ['Travailler en équipe','Prototyper rapidement'],
    'Collège, Lycée',
    '13-18 ans',
    '1 journée',
    '900',
    'Kits; mentors; matériel événementiel',
    'Robotique & IA',
    '#0a714e',
    'robotique_ia',
    'Événement;Hackathon;Pack',
    ARRAY ['hackathon','événement']
  ),
  (
    18,
    'anniversaire-tech',
    'Anniversaire Tech',
    'Animation anniversaire avec défis scientifiques et robotiques, matériel inclus.',
    ARRAY ['Coopérer','Résoudre défis ludiques'],
    'Enfants/Familles',
    '3',
    '250',
    'Kits thématiques; animateur; consommables',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/Anniversaire_Tech.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvQW5uaXZlcnNhaXJlX1RlY2guanBnIiwiaWF0IjoxNzc4Mjg3MDM0LCJleHAiOjE4NzI4OTUwMzR9.0ml9aBMDaegLhjFAXnCn-szq4ZT_f990w0HvTYNGSy0',
    '2026-05-08 00:00:00',
    'pack',
    'pack',
    18,
    '2026-05-08 17:59:19.171426+00',
    'Anniversaire Tech',
    'Formule événementielle pour anniversaire avec défis robotiques et expériences.',
    'Animation clé en main : 3 heures d''activités encadrées, matériel fourni, scénario ludique et goûter possible. Options : thème robotique, chimie, espace.',
    ARRAY ['Coopérer','Résoudre défis ludiques'],
    'Particuliers, familles',
    '7-12 ans',
    '3 heures',
    '250',
    'Kits thématiques; animateur; consommables',
    'Pack',
    'blue',
    'numerique_code',
    'Événement;Pack',
    ARRAY ['anniversaire','événement']
  ),
  (
    301,
    'planetarium-creation',
    'Création d''un Planétarium',
    'Concevoir et fabriquer un mini‑planétarium pédagogique : structure, projection et scénarios de visite.',
    ARRAY ['Comprendre constellations','Modéliser en 3D','Piloter optique et moteur'],
    'Collège/Lycée',
    '30',
    '3200',
    'Mini-projecteur; moteurs pas à pas; microcontrôleur; optiques; matériaux structurels',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/SYSTEME_SOLAIRE.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvU1lTVEVNRV9TT0xBSVJFLnBuZyIsImlhdCI6MTc3ODM0MDQ1NCwiZXhwIjoxODcyOTQ4NDU0fQ.Jvq8op3iUQvSw7sKhgEecgss7ziE4t8g9KQyJ9OblOQ',
    '2026-05-09 10:38:24.891259',
    'sciences',
    'pack',
    301,
    '2026-05-10 07:25:51.912942+00',
    'Création d''un Planétarium',
    'Mini‑planétarium pédagogique',
    'Atelier complet : conception mécanique, modélisation 3D, électronique et programmation de la projection. Déroulé modulable sur 10 à 30 séances selon format.',
    ARRAY ['Concevoir structure','Programmer pilotage','Créer scénario pédagogique'],
    'Écoles, collèges, lycées',
    '12-17 ans',
    '10 séances / trimestre;20 séances (2T);30 séances (3T)',
    '3200',
    'Mini-projecteur; moteurs; microcontrôleur; matériaux structurels',
    'Sciences & Expériences',
    '#0097b2',
    'sciences_experiences',
    'Cycle;Pack',
    ARRAY ['astronomie','planétarium','3D']
  ),
  (
    302,
    'mini-ville-intelligente',
    'Mini Ville Intelligente',
    'Concevoir une maquette de ville intelligente intégrant capteurs, gestion d''énergie, mobilité et services connectés.',
    ARRAY ['Concevoir réseaux de capteurs','Optimiser consommation énergétique','Développer interfaces de supervision'],
    'Collège/Lycée',
    '20',
    '2600',
    'ESP32/Arduino; capteurs (température, luminosité, qualité air); relais; maquette; routeur local; tablettes',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/smart_city.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvc21hcnRfY2l0eS5wbmciLCJpYXQiOjE3NzgzNDE1ODIsImV4cCI6MTg3Mjk0OTU4Mn0.lP_vc7eqQD5nHBgja04uZTGEBWXNksEWR9G1UQW0aYk',
    '2026-05-09 10:38:24.891259',
    'ecologie-vie',
    'pack',
    302,
    '2026-05-10 07:25:51.912942+00',
    'Mini Ville Intelligente',
    'Maquette de ville connectée et durable',
    'Atelier interdisciplinaire : architecture, IoT, gestion d''énergie et data. Les élèves conçoivent quartiers intelligents, capteurs et tableaux de bord pour piloter la ville.',
    ARRAY ['Installer capteurs urbains','Simuler gestion énergie','Créer tableau de bord'],
    'Collèges, lycées, collectivités',
    '12-17 ans',
    '10 séances / trimestre;20 séances (2T);30 séances (3T)',
    '2600',
    'ESP32/Arduino; capteurs; relais; maquette; routeur',
    'Robotique & IA',
    '#4ca626',
    'robotique_ia',
    'Cycle;Pack',
    ARRAY ['ville-intelligente','iot','énergie']
  ),
  (
    303,
    'desamorçage-fictif',
    'Désamorçage Pédagogique (scénario fictif)',
    'Scénario pédagogique non violent pour développer logique, électronique et travail d''équipe via une boîte sécurisée à "désamorcer".',
    ARRAY ['Résoudre énigmes logiques','Monter circuits basse tension','Coordonner en équipe'],
    'Collège/Lycée',
    '10',
    '1800',
    'Boîtes sécurisées; microcontrôleurs; capteurs; chronomètres; supports pédagogiques',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/desamorcer_bombe_2.webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvZGVzYW1vcmNlcl9ib21iZV8yLndlYnAiLCJpYXQiOjE3NzgzNDM3NzcsImV4cCI6MTg3Mjk1MTc3N30.yB-nLcy5QSaFcMXilhmweMM9074X7PAz-w5UzgNQxz8',
    '2026-05-09 10:38:24.891259',
    'numerique-code',
    'pack',
    303,
    '2026-05-10 07:25:51.912942+00',
    'Désamorçage Pédagogique',
    'Scénario fictif de désamorçage sécurisé',
    'Atelier encadré et sécurisé : énigmes logiques, circuits basse tension et coordination d''équipe. Strictement fictif et sans danger.',
    ARRAY ['Analyser indices','Construire circuits','Gérer stress et communication'],
    'Collèges, lycées',
    '12-17 ans',
    '10 séances / trimestre',
    '1800',
    'Boîtes sécurisées; microcontrôleurs; capteurs; chronomètres',
    'Numérique & Code',
    '#4910bc',
    'numerique_code',
    'Cycle;Pack',
    ARRAY ['logique','circuits','teamwork']
  ),
  (
    304,
    'jeu-plateau-connecte',
    'Jeu de Plateau Connecté',
    'Concevoir un jeu de plateau intégrant capteurs, scoring électronique et application compagnon.',
    ARRAY ['Designer gameplay','Intégrer capteurs','Développer appli compagnon'],
    'Collège/Lycée',
    '10',
    '1900',
    'Capteurs tactiles; NFC; microcontrôleurs; tablettes; imprimante 3D',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/Jeu_plateau_1.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvSmV1X3BsYXRlYXVfMS5qcGciLCJpYXQiOjE3NzgzNDM5MjMsImV4cCI6MTg3Mjk1MTkyM30.67vRehx55NkM6leOgnxKLKTn1jw5aQbQG4gzH9MnznQ',
    '2026-05-09 10:38:24.891259',
    'numerique-code',
    'pack',
    304,
    '2026-05-10 07:25:51.912942+00',
    'Jeu de Plateau Connecté',
    'Prototype de jeu hybride physique/numérique',
    'Atelier de design et prototypage : règles, capteurs, scoring et application compagnon. Tests utilisateurs et équilibrage inclus.',
    ARRAY ['Prototyper règles','Intégrer électronique','Tester UX'],
    'Collèges, lycées, makerspaces',
    '12-17 ans',
    '10 séances / trimestre',
    '1900',
    'Capteurs tactiles; NFC; microcontrôleurs; tablettes',
    'Numérique & Code',
    '#4910bc',
    'numerique_code',
    'Cycle;Pack',
    ARRAY ['jeu','prototype','nfc']
  ),
  (
    305,
    'mini-vehicule-autonome',
    'Mini Véhicule Autonome',
    'Concevoir et programmer un véhicule autonome miniature : capteurs, asservissement et navigation.',
    ARRAY ['Assembler châssis','Programmer asservissement','Implémenter évitement d''obstacles'],
    'Collège/Lycée',
    '12',
    '2200',
    'Kits robotique; capteurs ultrasons; encodeurs; batteries; PC',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/Mini_Vehicule_Autonome.avif?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvTWluaV9WZWhpY3VsZV9BdXRvbm9tZS5hdmlmIiwiaWF0IjoxNzc4MzQzOTgyLCJleHAiOjE4NzI5NTE5ODJ9.xO6Uvtk1J_5SfBKk8a5xFCZgA1MeOn4Kw7ge04deOss',
    '2026-05-09 10:38:24.891259',
    'robotique-ia',
    'pack',
    305,
    '2026-05-10 07:25:51.912942+00',
    'Mini Véhicule Autonome',
    'Robot véhicule autonome miniature',
    'Atelier robotique complet : mécanique, capteurs, asservissement et algorithmes de navigation. Compétition interne possible en fin de cycle.',
    ARRAY ['Concevoir châssis','Programmer capteurs','Optimiser trajectoire'],
    'Collèges, lycées, makerspaces',
    '12-17 ans',
    '10 séances / trimestre',
    '2200',
    'Kits robotique; capteurs; batteries; PC',
    'Robotique & IA',
    '#0a714e',
    'robotique_ia',
    'Cycle;Pack',
    ARRAY ['robotique','autonome','capteurs']
  ),
  (
    306,
    'robot-cuisine-multifonctions',
    'Robot de Cuisine Multifonctions (Boîte‑atelier)',
    'Concevoir une boîte robotisée capable d''exécuter tâches simples (mélanger, distribuer, minuterie) en intégrant mécanique, électronique et UX.',
    ARRAY ['Concevoir mécanismes simples','Piloter actionneurs','Documenter sécurité alimentaire'],
    'Collège/Lycée',
    '12',
    '2400',
    'Microcontrôleurs; moteurs; capteurs de niveau; boîtes sécurisées; matériaux non alimentaires',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/Robot_Cuisine_Multifonctions.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvUm9ib3RfQ3Vpc2luZV9NdWx0aWZvbmN0aW9ucy5qcGciLCJpYXQiOjE3NzgzNDQ4MjcsImV4cCI6MTg3Mjk1MjgyN30.Fr42xx7C_iJfTJYJk-dYtGM2YWsUf_qNqsRyxP9L33o',
    '2026-05-09 10:38:24.891259',
    'sciences',
    'pack',
    306,
    '2026-05-10 07:25:51.912942+00',
    'Robot de Cuisine Multifonctions',
    'Boîte robotisée pour tâches simples',
    'Atelier interdisciplinaire : mécanique, électronique et design produit. Tests hygiène simulés et documentation sécurité.',
    ARRAY ['Concevoir mécanisme','Programmer séquences','Rédiger manuel sécurité'],
    'Collèges, lycées, makerspaces',
    '12-17 ans',
    '10 séances / trimestre',
    '2400',
    'Microcontrôleurs; moteurs; capteurs; boîtes sécurisées',
    'Sciences & Expériences',
    '#0097b2',
    'sciences_experiences',
    'Cycle;Pack',
    ARRAY ['robotique','mécanique','automatisation']
  ),
  (
    311,
    'escape-cyber-attaque',
    'Escape Game : Cyber‑Attaque au Collège',
    'Scénario pédagogique : identifier et neutraliser une attaque simulée sur le réseau de l''établissement.',
    ARRAY ['Comprendre phishing','Appliquer chiffrement simple','Analyser trafic réseau'],
    'Collège',
    '10',
    '1800',
    'PC; simulateur réseau; kits pédagogiques',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/cyberattaque_college.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvY3liZXJhdHRhcXVlX2NvbGxlZ2UucG5nIiwiaWF0IjoxNzc4MzQ0NzcyLCJleHAiOjE4NzI5NTI3NzJ9.GL6o8JJaied-7z8KToiSTS9L46czB6dXbVkFSBmhzkU',
    '2026-05-09 10:38:24.891259',
    'numerique-code',
    'module',
    311,
    '2026-05-10 07:25:51.912942+00',
    'Escape Game - Cyber‑Attaque',
    'Simulation de cyberattaque pour collégiens',
    'Atelier ludique et sécurisé : cryptographie, phishing, mini‑CTF et sécurisation. Déroulé modulable sur 1 à 3 trimestres.',
    ARRAY ['Déchiffrer messages','Identifier phishing','Sécuriser système'],
    'Collège',
    '12-15 ans',
    '10 séances / trimestre',
    '1800',
    'PC; simulateur réseau; supports pédagogiques',
    'Numérique & Code',
    '#4910bc',
    'numerique_code',
    'Cycle;Pack',
    ARRAY ['cybersécurité','escape','ctf']
  ),
  (
    312,
    'escape-robot-labyrinthe',
    'Escape Game : Le Robot Perdu dans le Labyrinthe',
    'Un robot d''exploration est coincé dans un labyrinthe. Les élèves doivent le reprogrammer et le guider vers la sortie.',
    ARRAY ['Programmer séquences','Utiliser capteurs','Optimiser trajectoire'],
    'Primaire/Collège',
    '10',
    '1700',
    'Kits robotique; capteurs ultrasons; tablettes',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/Robot_Perdu_Labyrinthe.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvUm9ib3RfUGVyZHVfTGFieXJpbnRoZS5qcGciLCJpYXQiOjE3NzgzNDQ5ODcsImV4cCI6MTg3Mjk1Mjk4N30.sPS0EvYI5BR0B3DMn9JvSfom8HINjmvmcFgAyfvgcSo',
    '2026-05-09 10:38:24.891259',
    'robotique-ia',
    'module',
    312,
    '2026-05-10 07:25:51.912942+00',
    'Escape Game - Robot dans le Labyrinthe',
    'Reprogrammer un robot pour sortir d''un labyrinthe',
    'Atelier progressif : programmation par blocs, capteurs et optimisation. Déroulé modulable sur 1 à 3 trimestres selon profondeur.',
    ARRAY ['Programmer déplacements','Calibrer capteurs','Cartographier parcours'],
    'Primaire/Collège',
    '9-14 ans',
    '10 séances / trimestre',
    '1700',
    'Kits robotique; capteurs; tablettes',
    'Robotique & IA',
    '#0a714e',
    'robotique_ia',
    'Cycle;Pack',
    ARRAY ['robotique','labyrinthe','programmation']
  ),
  (
    313,
    'escape-labo-quarantaine',
    'Escape Game : Laboratoire en Quarantaine',
    'Un incident a eu lieu dans un laboratoire. Les élèves doivent analyser échantillons, identifier un polluant et rétablir la sécurité.',
    ARRAY ['Réaliser tests pH','Analyser données','Rédiger protocole'],
    'Primaire/Collège',
    '10',
    '1750',
    'Kits chimie non toxiques; loupes; capteurs; fiches terrain',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/Escape_Game-Laboratoire_en_Quarantaine.avif?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvRXNjYXBlX0dhbWUtTGFib3JhdG9pcmVfZW5fUXVhcmFudGFpbmUuYXZpZiIsImlhdCI6MTc3ODM0MzcyMCwiZXhwIjoxODcyOTUxNzIwfQ.xNPaeW9tV0p0zCK2lqOmX4hmMPTIbeeoT6qipeaTYW0',
    '2026-05-09 10:38:24.891259',
    'ecologie-vie',
    'module',
    313,
    '2026-05-10 07:25:51.912942+00',
    'Escape Game - Laboratoire en Quarantaine',
    'Analyser et sécuriser un laboratoire fictif',
    'Atelier sécurisé : tests chimiques simples, analyse de données et protocole scientifique. Déroulé modulable sur 1 à 3 trimestres.',
    ARRAY ['Mesurer pH','Interpréter courbes','Proposer protocole'],
    'Collège',
    '11-15 ans',
    '10 séances / trimestre',
    '1750',
    'Kits chimie non toxiques; loupes; capteurs',
    'Écologie & Sciences de la Vie',
    '#4ca626',
    'ecologie_sciences_vie',
    'Cycle;Pack',
    ARRAY ['chimie','biologie','analyse']
  ),
  (
    314,
    'escape-mission-ecologie',
    'Escape Game - Mission Écologie : Sauver la Ville',
    'La ville entre en crise énergétique. Les élèves doivent rétablir l''équilibre : eau, énergie, pollution, biodiversité.',
    ARRAY ['Construire prototype solaire','Calculer empreinte carbone','Simuler reforestation'],
    'Collège/Lycée',
    '10',
    '1850',
    'Kits solaire; éolienne miniature; capteurs; supports pédagogiques',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/EscapeGameMission_Ecologie_Sauver_Ville.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvRXNjYXBlR2FtZU1pc3Npb25fRWNvbG9naWVfU2F1dmVyX1ZpbGxlLmpwZyIsImlhdCI6MTc3ODM0NTc3NiwiZXhwIjoxODcyOTUzNzc2fQ.xUi5-ZFgF-aRFWxKaFLeNukjF6yPflGzCYVMb5q89aA',
    '2026-05-09 10:38:24.891259',
    'ecologie-vie',
    'module',
    314,
    '2026-05-10 07:25:51.912942+00',
    'Escape Game - Mission Écologie',
    'Prototyper solutions pour une ville durable',
    'Atelier pratique : prototypes énergétiques, collecte de données et simulation d''impact. Déroulé modulable sur 1 à 3 trimestres.',
    ARRAY ['Construire prototype','Collecter données','Optimiser consommation'],
    'Collège/Lycée',
    '12-17 ans',
    '10 séances / trimestre',
    '1850',
    'Kits solaire; éolienne; capteurs; supports',
    'Écologie & Sciences de la Vie',
    '#4ca626',
    'ecologie_sciences_vie',
    'Cycle;Pack',
    ARRAY ['écologie','énergie','ville']
  ),
  (
    315,
    'escape-mission-spatiale',
    'Escape Game - Mission Spatiale : Alunissage d''Urgence',
    'Un module lunaire doit se poser en urgence. Les élèves recalculent trajectoire, réparent systèmes et pilotent un rover.',
    ARRAY ['Calculer trajectoire','Construire maquette fusée','Piloter rover'],
    'Collège/Lycée',
    '12',
    '2200',
    'Simulateur orbital; kits fusée eau; rover; PC',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/MissionSpatiale-Alunissage_Urgence.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvTWlzc2lvblNwYXRpYWxlLUFsdW5pc3NhZ2VfVXJnZW5jZS5qcGciLCJpYXQiOjE3NzgzNzY5ODYsImV4cCI6MTg3Mjk4NDk4Nn0.5e04_MvntZ3v5gu_1iM48Hu8cStDDjM_C6_8mc1yWg0',
    '2026-05-09 10:38:24.891259',
    'espace-aeronautique',
    'module',
    315,
    '2026-05-10 07:25:51.912942+00',
    'Escape Game - Mission Spatiale',
    'Simulation d''alunissage et mission rover',
    'Atelier interdisciplinaire : physique, calculs, construction et pilotage. Déroulé modulable sur 1 à 3 trimestres.',
    ARRAY ['Calculer poussée','Simuler orbite','Piloter rover'],
    'Collège/Lycée',
    '13-17 ans',
    '10 séances / trimestre',
    '2200',
    'Simulateur orbital; kits fusée eau; rover; PC',
    'Espace & Aéronautique',
    '#004aad',
    'espace_aeronotique',
    'Cycle;Pack',
    ARRAY ['espace','fusées','rover']
  ),
  (
    316,
    'escape-ia-deraille',
    'Escape Game - L''IA Déraille : Sauver le Système',
    'Une IA de gestion devient instable. Les élèves doivent diagnostiquer biais, corriger modèles et rétablir le système.',
    ARRAY ['Identifier biais','Nettoyer données','Réentraîner modèle simple'],
    'Collège/Lycée',
    '12',
    '2300',
    'Ordinateurs; datasets pédagogiques; outils no-code',
    'https://orzfuxasrbpkcaqvgvah.supabase.co/storage/v1/object/sign/images-ateliers/IADerailleSauver-Systeme.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80MzVkYjM4Ni1kN2Q5LTQwZWEtYmE5Mi04MTMwOTRhZjg2YTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZXMtYXRlbGllcnMvSUFEZXJhaWxsZVNhdXZlci1TeXN0ZW1lLmpwZWciLCJpYXQiOjE3NzgzNDU5MTIsImV4cCI6MTg3Mjk1MzkxMn0.ZEVVeFZcc0L8a--v_Pc1RyVuGI8sUbWdtJR4Wzest8c',
    '2026-05-09 10:38:24.891259',
    'robotique-ia',
    'module',
    316,
    '2026-05-10 07:25:51.912942+00',
    'Escape Game - L''IA Déraille',
    'Diagnostiquer et corriger une IA instable',
    'Atelier pratique : exploration des biais, nettoyage de données, entraînement et débat éthique. Déroulé modulable sur 1 à 3 trimestres.',
    ARRAY ['Analyser biais','Nettoyer dataset','Évaluer modèle'],
    'Collège/Lycée',
    '13-17 ans',
    '10 séances / trimestre',
    '2300',
    'Ordinateurs; datasets; outils no-code',
    'Robotique & IA',
    '#0a714e',
    'robotique_ia',
    'Cycle;Pack',
    ARRAY ['IA','éthique','données']
  );
